### ISSUE TITLE
reloading-related WebSock problem stops metaor from booting

### ISSUE THREAD

**Issue by csillag** [gadicc/meteor-hmr#132]
## Meteor can't start up because of a WebSock problem

I am trying to add meteor-hmr to an existing Meteor project.
Here are the changes in the `.meteor/packages file`:

```
 standard-minifier-css@1.2.0_1   # CSS minifier run for production mode
 standard-minifier-js@1.2.0_1    # JS minifier run for production mode
 es5-shim@4.6.14_1                # ECMAScript 5 compatibility for older browsers.
-ecmascript@0.5.8_1              # Enable ECMAScript2015+ syntax in app code
+gadicc:ecmascript-hot
 shell-server@0.2.1            # Server-side component of the `meteor shell` command
 autopublish@1.0.7             # Publish all data to the clients (for prototyping)
```

... and in the `packages.json` file:

```
+  },
+  "devDependencies": {
+    "babel-plugin-react-transform": "^2.0.2",
+    "babel-preset-meteor": "^6.13.0",
+    "react-transform-catch-errors": "^1.0.2",
+    "react-transform-hmr": "^1.0.4",
+    "redbox-react": "^1.3.2"
```

Now, this is what I get when I try to launch the app:

```
meteor run
[[[[[ /whatever/app ]]]]]

=> Started proxy.                             
   Determining active plugins                |
[gadicc:hot-build] (p34): Lost connection to accelerator, trying to reconnect...
=> Starting gadicc:hot-build Accelerator (p34) on port 3002.

   Building the application                  |
[gadicc:hot-build] (p34): Reconnected
/home/user/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/home/user/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/WebSocket.js:219:16)
    at WebSocket.<anonymous> (packages/gadicc_hot-build/accelerator.js:63:1)
    at emitNone (events.js:67:13)
    at WebSocket.emit (events.js:166:7)
    at WebSocket.establishConnection (/home/user/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/WebSocket.js:887:8)
    at ClientRequest.upgrade (/home/user/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/WebSocket.js:778:25)
    at ClientRequest.g (events.js:260:16)
    at emitThree (events.js:97:13)
    at ClientRequest.emit (events.js:175:7)
    at Socket.socketOnData (_http_client.js:354:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

[gadicc:hot] Accelerator (p34): disconnect event received, exiting.

```

## Environment

* Meteor version: 1.4.1.2
* ecmascript-hot version: 1.3.2-refactor.12
* Operating System: Debian Linux

## Supporting files

<details>
<summary>`.meteor/packages`</summary>
```
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12_1                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0_1   # CSS minifier run for production mode
standard-minifier-js@1.2.0_1    # JS minifier run for production mode
es5-shim@4.6.14_1                # ECMAScript 5 compatibility for older browsers.
shell-server@0.2.1            # Server-side component of the `meteor shell` command

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
meteortypescript:compiler
twbs:bootstrap
coffeescript
nathantreid:css-modules
gadicc:ecmascript-hot

```
</details><details>
<summary>`.meteor/versions`</summary>
```
allow-deny@1.0.5
autopublish@1.0.7
autoupdate@1.2.11
babel-compiler@6.9.1_1
babel-runtime@0.1.11_1
barbatus:typescript@0.3.4_1
barbatus:typescript-compiler@0.6.11
barbatus:typescript-runtime@0.1.2
base64@1.0.9
binary-heap@1.0.9
blaze@2.1.9
blaze-html-templates@1.0.5
blaze-tools@1.0.10
boilerplate-generator@1.0.10
caching-compiler@1.1.7_1
caching-html-compiler@1.0.7
callback-hook@1.0.9
check@1.2.3
coffeescript@1.2.4_2
ddp@1.2.5
ddp-client@1.2.9
ddp-common@1.2.6
ddp-server@1.2.10
deps@1.0.12
diff-sequence@1.0.6
ecmascript@0.5.8_1
ecmascript-runtime@0.3.14_1
ejson@1.0.12
es5-shim@4.6.14_1
fastclick@1.0.12
gadicc:babel-compiler-babelrc@6.6.4_2
gadicc:ecmascript-hot@1.3.2-refactor.12
gadicc:hot@0.0.25
gadicc:hot-build@0.0.14
gadicc:modules-runtime-hot@0.6.3_6
geojson-utils@1.0.9
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.1.8
id-map@1.0.8
insecure@1.0.7
jquery@1.11.9
launch-screen@1.0.12
livedata@1.0.18
logging@1.1.15_1
meteor@1.2.17_1
meteor-base@1.0.4
meteorhacks:inject-initial@1.0.4
meteortypescript:compiler@3.2.2
minifier-css@1.2.14_1
minifier-js@1.2.14_1
minimongo@1.0.17
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.7.6_1
modules-runtime@0.7.6_1
mongo@1.1.12_5
mongo-id@1.0.5
nathantreid:css-modules@2.2.2
nathantreid:css-modules-import-path-helpers@0.1.4
npm-mongo@2.2.10_1
observe-sequence@1.0.13
ordered-dict@1.0.8
promise@0.8.7
ramda:ramda@0.19.0
random@1.0.10
reactive-var@1.0.10
reload@1.1.10
retry@1.0.8
routepolicy@1.0.11
shell-server@0.2.1
spacebars@1.0.13
spacebars-compiler@1.0.13
standard-minifier-css@1.2.1
standard-minifier-js@1.2.0_1
templating@1.2.15
templating-compiler@1.2.15
templating-runtime@1.2.15
templating-tools@1.0.5
tmeasday:check-npm-versions@0.3.1
tracker@1.1.0
twbs:bootstrap@3.3.6
ui@1.0.12
underscore@1.0.9
url@1.0.10
webapp@1.3.11_1
webapp-hashing@1.0.9

```
</details><details>
<summary>`packages.json`</summary>
```js
{
  "name": "app",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "axios": "^0.15.0",
    "classnames": "^2.2.5",
    "immutable": "^3.8.1",
    "meteor-build-client": "^0.4.1",
    "meteor-node-stubs": "~0.2.0",
    "node-feedparser": "^1.0.1",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-redux": "^4.4.5",
    "redux": "^3.6.0",
    "redux-axios-middleware": "^3.0.0",
    "valid-url": "^1.0.9",
    "xml2js": "^0.4.17"
  },
  "devDependencies": {
    "babel-plugin-react-transform": "^2.0.2",
    "babel-preset-meteor": "^6.13.0",
    "react-transform-catch-errors": "^1.0.2",
    "react-transform-hmr": "^1.0.4",
    "redbox-react": "^1.3.2"
  }
}

```
</details><details>
<summary>`.babelrc` (if you modified it)</summary>
```js
Not modified.
```
</details><details>
<summary>`client/.babelrc` (if you modified it)</summary>
```js
doesn't exist.
```
</details><details>
<summary>`server/.babelrc` (if you created it)</summary>
```js
doesn't exist.
```
</details>

**Comment by csillag** [comment]
I realized the problem was that I have added the package by executing

    meteor add gadicc:ecmascript-hot

instead of

    meteor add gadicc:ecmascript-hot@2.0.0-beta.3

After explicitly installing the latest version of the module, the problem described above is resolved.
