### ISSUE TITLE
[Windows] Error: watch ENOENT

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-hmr#41]
And maybe others :)  Would love some help from Windows users.  Otherwise will setup a Windows VM and look into this when I have a chance.

**Comment by Vincent-P** [comment]
I have this error by just adding your package to mantra-sample-blog : 
```
=> Started proxy.
=> Started MongoDB.
   Building the application                  /
module.js:340
    throw err;
          ^
Error: Cannot find module 'undefined\dev_bundle\lib\node_modules\fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at meteorRequire (C:\Users\vince\AppData\Local\.meteor\packages\gadicc_ecmascript-hot\1.3.2-refactor.6\plugin.compile-ecmascript-hot.os\npm\node_modules\meteor\gadicc_hot-build\node_modules\meteor-hotload-accelerator\lib\accelerator.js:38:10)
    at Object.<anonymous> (C:\Users\vince\AppData\Local\.meteor\packages\gadicc_ecmascript-hot\1.3.2-refactor.6\plugin.compile-ecmascript-hot.os\npm\node_modules\meteor\gadicc_hot-build\node_modules\meteor-hotload-accelerator\lib\accelerator.js:41:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
   Building the application                  -
[gadicc:hot-build] (nZ2): Unhandled websocket err! { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

**Comment by Vincent-P** [comment]
It seems like this is undefined :
```js
// meteor-hmr/accelerator/src/accelerator.js:15

const meteorToolPath = process.argv[4];
```

**Comment by gadicc** [comment]
@Vincent-P I'll address this in https://github.com/gadicc/meteor-hmr/issues/56.

**Comment by Vincent-P** [comment]
The problem is with toDosPath function in hot-build/hot-server.js.

**Comment by Vincent-P** [comment]
There :
```js
Hot.prototype.processFilesForTarget = function(inputFiles) {
...
      file = convertToOSPath(path.join(
        inputFile._resourceSlot.packageSourceBatch.sourceRoot,
        inputFile.getPathInPackage()
      ));
 ...
}
```
In Windows I have this : 
```js
// /E/Code/WEB/mantra-sample-blog-app
inputFile._resourceSlot.packageSourceBatch.sourceRoot

// lib/collections.js
inputFile.getPathInPackage()

// \E\Code\WEB\mantra-sample-blog-app\lib\collections.js
path.join(inputFile._resourceSlot.packageSourceBatch.sourceRoot, inputFile.getPathInPackage())

or
///E/Code/WEB/mantra-sample-blog-app/lib/collections.js
inputFile._resourceSlot.packageSourceBatch.sourceRoot + '/' + inputFile.getPathInPackage()

```

So `path.join()` replaces `/` with `\` but `toDosPath` expects a `/` : 
```js
if (p[0] === '/' && ! partialPath) {
    if (! /^\/[A-Za-z](\/|$)/.test(p))
      throw new Error("Surprising path: " + p);
    // transform a previously windows path back
    // "/C/something" to "c:/something"
    p = p[1] + ":" + p.slice(2);
  }
```

So replacing `path.join` by a string concatenation works,
```js
file = convertToOSPath(path.join(
    inputFile._resourceSlot.packageSourceBatch.sourceRoot,
    inputFile.getPathInPackage()
));

// to
file = convertToOSPath(inputFile._resourceSlot.packageSourceBatch.sourceRoot + '/' + inputFile.getPathInPackage());
```

**Comment by gadicc** [comment]
oh wow, amazingly helpful!  thanks!!

**Comment by Vincent-P** [comment]
So now it seems to work, the app can start but I still have no idea on how to use this with Mantra.
I have replaced `ecmascript`, installed `react-hot-loader` and `redbox-react`, add `"react-hot-loader/babel"` to `.babelrc` but I dont know where I have to add the `AppContainer`...

**Comment by gadicc** [comment]
Mmm let me actually make a quick repo of mantra-sample-blog-app, I think a lot of people would benefit from it.

**Comment by gadicc** [comment]
Sorry I said quickly but I ran out of time and will only get to this tomorrow.  I guess you'd put the AppContainer where you have the `mount` commands, possibly multiple times for each route action, I haven't actually looked yet how RHLv3 plays with mantra, but if you don't get it working I'll have a repo up tomorrow (I'm in GMT+2).

**Comment by Vincent-P** [comment]
Okay I'll try thank you.

**Comment by gadicc** [comment]
@Vincent-P, check out https://github.com/gadicc/meteor-hmr/issues/60.

Unfortunately it's not so neat... the Mantra design isn't so compatible with react-hot-loader.  Maybe we can find a compromise in the future.
