### ISSUE TITLE
[Windows] undefined\dev_bundle\lib\node_modules\fibers in refactor branch

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-hmr#56]
Originally described by @Vincent-P [here](https://github.com/gadicc/meteor-hmr/issues/41#issuecomment-215122617):

> Error: Cannot find module 'undefined\dev_bundle\lib\node_modules\fibers'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at meteorRequire (C:\Users\vince\AppData\Local\.meteor\packages\gadicc_ecmascript-hot\1.3.2-refactor.6\plugin.compile-ecmascript-hot.os\npm\node_modules\meteor\gadicc_hot-build\node_modules\meteor-hotload-accelerator\lib\accelerator.js:38:10)
    at Object.<anonymous> (C:\Users\vince\AppData\Local\.meteor\packages\gadicc_ecmascript-hot\1.3.2-refactor.6\plugin.compile-ecmascript-hot.os\npm\node_modules\meteor\gadicc_hot-build\node_modules\meteor-hotload-accelerator\lib\accelerator.js:41:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

> It seems like this is undefined :

> ```js
// meteor-hmr/accelerator/src/accelerator.js:15
const meteorToolPath = process.argv[4];
```

Sorry, @Vincent-P, I feel like we're sending you around in hoops :(  I didn't realize you were on Windows, and we still have bugs on Windows.  As soon as the rest of the branch is stable I'll work on Windows support, unless there are some Windows developers who can help me first.  I'm modifying the README to make this clearer.  Appreciate your patience :)

**Comment by gadicc** [comment]
Your assessment is correct, I'll try see how we were figuring out that path and look at an alternative for Windows when I have a chance.  Just heading out now.

**Comment by Vincent-P** [comment]
I think I got it : 
```js
// meteor-hmr/accelerator/src/index.js:7
const meteorToolPath = process.env.OLDPWD;
```

This only works on *NIX systems.

**Comment by gadicc** [comment]
Thanks, @Vincent-P!  Hopefully fixed in next release.

**Comment by gadicc** [comment]
Just saw your edit now about Sanjo/meteor-meteor-file-helpers... wish I knew about this before!

**Comment by gadicc** [comment]
I'm still going to close this issue though, since I'm fairly confident my patch above works.  If not, can you please re-open?  Hope to publish the last batch of updates shortly.

**Comment by Vincent-P** [comment]
Yes it works !

**Comment by gadicc** [comment]
Awesome, thanks!
