### ISSUE TITLE
Issues running chimp

### ISSUE THREAD

**Issue by clayne11** [gadicc/meteor-hmr#62]
When I try to run my integration tests with `gadicc:ecmascript-hot` the tests crash with:

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] Error: Couldn't connect to selenium server
    at new RuntimeError (/Users/clayne/workspace/r3ntr_meteor/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/Users/clayne/workspace/r3ntr_meteor/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/Users/clayne/workspace/r3ntr_meteor/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (/Users/clayne/workspace/r3ntr_meteor/node_modules/webdriverio/node_modules/request/request.js:971:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at connectErrorNT (net.js:994:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

And sometimes:

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: text.split is not a function
    at /Users/clayne/workspace/r3ntr_meteor/node_modules/meteor-promise/fiber_pool.js:33:40
(node) warning: possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at [object Object].addListener (events.js:252:17)
    at [object Object].once (events.js:278:8)
    at /Users/clayne/workspace/r3ntr_meteor/node_modules/xolvio-ddp/lib/ddp-client.js:342:10
    at tryCatcher (/Users/clayne/workspace/r3ntr_meteor/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/clayne/workspace/r3ntr_meteor/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/clayne/workspace/r3ntr_meteor/node_modules/bluebird/js/main/promise.js:70:37)
    at [object Object].DDPClient.connect (/Users/clayne/workspace/r3ntr_meteor/node_modules/xolvio-ddp/lib/ddp-client.js:310:10)
    at Timeout._onTimeout (/Users/clayne/workspace/r3ntr_meteor/node_modules/xolvio-ddp/lib/ddp-client.js:114:58)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

When I switch to regular `ecmascript` I don't have this problem.

I tried changing the `HOT_PORT` burt that didn't work either.

**Comment by gadicc** [comment]
Do you get the same thing with ecmascript-hot but without `react-hot-loader/babel` and `react-hot-loader/patch` ?

**Comment by clayne11** [comment]
Closing in favor of https://github.com/gadicc/meteor-hmr/issues/63

**Comment by gadicc** [comment]
Great news, was trying to think what could be causing this and find time to install chimp, so glad it's working now.
