### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vincent-P** [gadicc/meteor-hmr#73]
## Description of Problem

I dont know if it's Windows specific but I have some ( random ? ) crashes.

```
Errors prevented startup:

While processing files with gadicc:ecmascript-hot (for target web.browser):
C:\Users\vince\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\ws\lib\WebSocket.js:181:16: not opened
  at WebSocket.send (C:\Users\vince\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\ws\lib\WebSocket.js:181:16)
  at Function.Hot.send (packages/gadicc_hot-build/accelerator.js:105:1)
  at [object Object].Hot.send (packages/gadicc_hot-build/hot-server.js:173:1)
  at [object Object].Hot.processFilesForTarget (packages/gadicc_hot-build/hot-server.js:209:1)
  at BabelCompiler.compiler.processFilesForTarget (packages/gadicc_hot-build/hot-server.js:155:1)


Your application has errors. Waiting for file change.
```

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: refactor 12
* Operating System: Windows 10

**Comment by Vincent-P** [comment]
And sometimes I get this : 
```
=> Meteor server restarted
   Building for web.browser                  /
[gadicc:hot-build] (sW4): Lost connection to accelerator, trying to reconnect...
=> Meteor server restarted
```

**Comment by gadicc** [comment]
Thanks, let's leave this open for now.  When I have a chance I'll review the websocket code and see if we can handle this a bit more cleanly (prime suspect: disconnect and then trying to send data before reconnect).  If you notice anything else please post here.

**Comment by gadicc** [comment]
I think this is fixed.  It will be in the upcoming `2.0.0-rc.0` release.  I'm closing for now because it's hard to see what's left for me to do with so many open issues :)  Please re-open if you see this again after using the next release (once it's out... next few days).
