### ISSUE TITLE
Breaks meteor update?

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-hmr#85]
```sh
$ meteor update
                                              
<runJavaScript-67>:82
    hot.processFilesForTarget(
        ^
TypeError: Object [object Object] has no method 'processFilesForTarget'
    at packages/node-modules-hot/plugin.js:67:1
    at /home/dragon/www/meteor-hmr/node-modules-hot/.npm/plugin/node-modules-hot/node_modules/recursive-readdir/index.js:71:20
    at Object.oncomplete (fs.js:108:15)
```

**Comment by gadicc** [comment]
in `node-modules-hot`.
