### ISSUE TITLE
Does the new update support FR SSR?

### ISSUE THREAD

**Issue by sammkj** [gadicc/meteor-hmr#86]
## Description of Problem

1. Error below pops up in the terminal console but everything is working fine in the browser.
2. When `view page source`, nothing is in the `body` tag.

* [x] I switched back to the regular `ecmascript` and the problem went away.

In the browser console:
```
AppContainer.dev.js:32React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports.
```

In the terminal console:
```
W20160513-09:48:18.266(-5)? (STDERR) Error when doing SSR. path:/: Object [object Object] has no method 'checkpoint'
W20160513-09:48:18.269(-5)? (STDERR) TypeError: Object [object Object] has no method 'checkpoint'
W20160513-09:48:18.269(-5)? (STDERR)     at [object Object].ReactCompositeComponentMixin.performInitialMountWithErrorHandling (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactCompositeComponent.js:256:34)
W20160513-09:48:18.269(-5)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactCompositeComponent.js:220:21)
W20160513-09:48:18.269(-5)? (STDERR)     at [object Object].wrapper [as mountComponent] (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactPerf.js:66:21)
W20160513-09:48:18.269(-5)? (STDERR)     at Object.ReactReconciler.mountComponent (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactReconciler.js:39:35)
W20160513-09:48:18.270(-5)? (STDERR)     at [object Object].ReactCompositeComponentMixin.performInitialMount (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactCompositeComponent.js:297:34)
W20160513-09:48:18.270(-5)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactCompositeComponent.js:222:21)
W20160513-09:48:18.270(-5)? (STDERR)     at [object Object].wrapper [as mountComponent] (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactPerf.js:66:21)
W20160513-09:48:18.270(-5)? (STDERR)     at /home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactServerRendering.js:38:38
W20160513-09:48:18.270(-5)? (STDERR)     at ReactServerRenderingTransaction.Mixin.perform (/home/skaxwng/code/meteor-todo/node_modules/react/lib/Transaction.js:136:20)
W20160513-09:48:18.270(-5)? (STDERR)     at renderToStringImpl (/home/skaxwng/code/meteor-todo/node_modules/react/lib/ReactServerRendering.js:36:24)
```

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: 1.3.2-refactor.12
* Operating System: Ubuntu

## Supporting files

<details>
<summary>`.meteor/packages`</summary>
```
meteor-base
mobile-experience
mongo
tracker

standard-minifier-css
standard-minifier-js
es5-shim
# ecmascript
gadicc:ecmascript-hot

random
kadira:dochead
meteorhacks:inject-initial
accounts-base
kadira:flow-router-ssr
```
</details><details>
<summary>`.meteor/versions`</summary>
```
accounts-base@1.2.7
allow-deny@1.0.4
autoupdate@1.2.9
babel-compiler@6.6.4
babel-runtime@0.1.8
base64@1.0.8
binary-heap@1.0.8
blaze@2.1.7
blaze-tools@1.0.8
boilerplate-generator@1.0.8
callback-hook@1.0.8
check@1.2.1
chuangbo:cookie@1.1.0
ddp@1.2.5
ddp-client@1.2.7
ddp-common@1.2.5
ddp-rate-limiter@1.0.4
ddp-server@1.2.6
deps@1.0.12
diff-sequence@1.0.5
ecmascript@0.4.3
ecmascript-runtime@0.2.10
ejson@1.0.11
es5-shim@4.5.10
fastclick@1.0.11
gadicc:babel-compiler-babelrc@6.6.4_2
gadicc:ecmascript-hot@1.3.2-refactor.12
gadicc:hot@0.0.25
gadicc:hot-build@0.0.14
gadicc:modules-runtime-hot@0.6.3_6
geojson-utils@1.0.8
hot-code-push@1.0.4
html-tools@1.0.9
htmljs@1.0.9
http@1.1.5
id-map@1.0.7
jquery@1.11.8
kadira:dochead@1.5.0
kadira:flow-router-ssr@3.13.0
launch-screen@1.0.11
livedata@1.0.18
localstorage@1.0.9
logging@1.0.12
meteor@1.1.14
meteor-base@1.0.4
meteorhacks:fast-render@2.14.0
meteorhacks:inject-data@2.0.0
meteorhacks:inject-initial@1.0.4
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
minifier-css@1.1.11
minifier-js@1.1.11
minimongo@1.0.16
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.6.1
modules-runtime@0.6.3
mongo@1.1.7
mongo-id@1.0.4
npm-mongo@1.4.43
observe-sequence@1.0.11
ordered-dict@1.0.7
promise@0.6.7
random@1.0.9
rate-limit@1.0.4
reactive-dict@1.1.7
reactive-var@1.0.9
reload@1.1.8
retry@1.0.7
routepolicy@1.0.10
service-configuration@1.0.9
spacebars@1.0.11
spacebars-compiler@1.0.11
standard-minifier-css@1.0.6
standard-minifier-js@1.0.6
tmeasday:check-npm-versions@0.3.1
tracker@1.0.13
ui@1.0.11
underscore@1.0.8
url@1.0.9
webapp@1.2.8
webapp-hashing@1.0.9
```
</details><details>
<summary>`packages.json`</summary>
```js
{
  "name": "meteor-todo",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "aphrodite": "^0.3.0",
    "apollo-client": "^0.1.6",
    "classnames": "^2.2.3",
    "domready": "^1.0.8",
    "express": "^4.13.4",
    "graphql": "^0.5.0",
    "graphql-tools": "^0.3.13",
    "http-proxy-middleware": "^0.14.0",
    "mantra-core": "^1.3.0",
    "material-ui": "^0.15.0-alpha.2",
    "meteor-node-stubs": "~0.2.0",
    "node-fetch": "^1.5.1",
    "node-waves": "^0.7.5",
    "react": "^15.0.1",
    "react-apollo": "^0.2.0",
    "react-appbar": "^1.0.1",
    "react-dom": "^15.0.1",
    "react-mounter-aphrodite": "^1.3.0",
    "react-no-ssr": "^1.0.1",
    "redux": "^3.4.0",
    "redux-log-slow-reducers": "0.0.2",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.7.4",
    "babel-eslint": "^6.0.0-beta.6",
    "babel-plugin-react-require": "^2.1.0",
    "babel-polyfill": "^6.7.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-meteor": "^6.6.6",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.3.13",
    "eslint": "^2.4.0",
    "eslint-config-airbnb": "^6.1.0",
    "eslint-plugin-graphql": "^0.2.3",
    "eslint-plugin-jsx-control-statements": "^1.1.0",
    "eslint-plugin-react": "^4.2.3",
    "jsx-control-statements": "^3.1.0",
    "raw-loader": "^0.5.1",
    "react-hot-loader": "^3.0.0-alpha.12",
    "redbox-react": "^1.2.0"
  }
}
```
</details><details>
<summary>`.babelrc` (if you modified it)</summary>
```js
{
  "presets": [
    "meteor",
    "es2015",
    "stage-0",
    "react",
  ],
  "plugins": [
    "react-require",
    "jsx-control-statements",
    "react-hot-loader/babel"
  ]
}
```
</details>

**Comment by gadicc** [comment]
Thanks for the detailed report.  If this is what I think, it's fixed in the latest react-hot-loader version.  Also, I just changed the docs to make this a real dependency rather than devDependency, since it needs to be bundled with your built project.  So can you try:

```
npm rm --save-dev react-hot-loader
npm i --save react-hot-loader@^3.0.0-beta.2
```

and report back.  If it's not this we'll figure it out.  Definitely want to support FR SSR by the time `rc.0` ships (in the next few days).

**Comment by sammkj** [comment]
I tried your suggestion and the problem still persists.

**Comment by gadicc** [comment]
Thanks for confirming.  For this and #88, I need some help.  Is the code for your app cloneable on github?  Or can you make a small reproduction?  I don't use flow-router-ssr in any of my projects and I'm struggling to get it set up here.

**Comment by sammkj** [comment]
I set up a very crude repro [here](https://github.com/sammkj/hmr-repro). Let me know if you want something more.

**Comment by sammkj** [comment]
* https://github.com/gaearon/react-hot-loader/issues/283

**Comment by gadicc** [comment]
Thanks for figuring out where the actual problem is!  Great help!  I've cloned the repo, but this is going to take some work.  I'm going to focus for now on getting meteor-hmr stable out, and hopefully react-hot-loader might get this fixed on it's own; otherwise with everything else working I'm going to try figure it out.

**Comment by sammkj** [comment]
This should be fixed with the new React release 15.1.0. I will double check this tomorrow.

**Comment by sammkj** [comment]
I tested it and it's throwing a new error:

```
W20160526-10:06:44.578(-5)? (STDERR) Warning: exception thrown by devtool while handling onSetChildren: Maximum call stack size exceeded
```

Do you have any ideas on this? I can't seem to find anything related to this.
