### ISSUE TITLE
Does not run in test mode

### ISSUE THREAD

**Issue by myknbani** [gadicc/meteor-hmr#96]
## Does not run tests

It emits the following errors in test mode (`meteor test --driver-package practicalmeteor:mocha -p 3100`)

```
TypeError: Arguments to path.join must be strings
W20160522-15:58:46.137(8)? (STDERR)     at path.js:360:15
W20160522-15:58:46.138(8)? (STDERR)     at Array.filter (/home/mykvanfifi/.meteor/packages/es5-shim/.4.5.10.jjty9l++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:499:48)
W20160522-15:58:46.138(8)? (STDERR)     at Object.exports.join (path.js:358:36)
W20160522-15:58:46.138(8)? (STDERR)     at Object.MeteorFilesHelpers.getPackageVersions (packages/sanjo_meteor-files-helpers/meteor_files_helpers.js:84:1)
W20160522-15:58:46.138(8)? (STDERR)     at Object.getPackageVersions (packages/underscore/underscore.js:665:1)
W20160522-15:58:46.138(8)? (STDERR)     at Object.MeteorFilesHelpers.getPackageVersion (packages/sanjo_meteor-files-helpers/meteor_files_helpers.js:100:1)
W20160522-15:58:46.139(8)? (STDERR)     at Package (packages/gadicc_babel-compiler-babelrc/hotVersionCheck.js:14:1)
```

It works with other compilers that support decorators like `pbastowski:angular-babel`. 

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: not using it
* Operating System: Linux Mint 17.3

### .meteor/packages

```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.

autopublish             # Publish all data to the clients (for prototyping)
insecure                # Allow all DB writes from clients (for prototyping)
angular-templates
practicalmeteor:mocha
fourseven:scss
gadicc:ecmascript-babelrc
```

### .meteor/versions

```
allow-deny@1.0.4
angular-templates@1.0.2
autopublish@1.0.7
autoupdate@1.2.9
babel-compiler@6.6.4
babel-runtime@0.1.8
base64@1.0.8
binary-heap@1.0.8
blaze@2.1.7
blaze-tools@1.0.8
boilerplate-generator@1.0.8
caching-compiler@1.0.4
caching-html-compiler@1.0.6
callback-hook@1.0.8
check@1.2.1
coffeescript@1.0.17
ddp@1.2.5
ddp-client@1.2.7
ddp-common@1.2.5
ddp-server@1.2.6
deps@1.0.12
diff-sequence@1.0.5
ecmascript@0.4.3
ecmascript-runtime@0.2.10
ejson@1.0.11
es5-shim@4.5.10
fastclick@1.0.11
fourseven:scss@3.4.3
gadicc:babel-compiler-babelrc@6.6.4_5
gadicc:ecmascript-babelrc@0.4.3_3
geojson-utils@1.0.8
hot-code-push@1.0.4
html-tools@1.0.9
htmljs@1.0.9
http@1.1.5
id-map@1.0.7
insecure@1.0.7
jquery@1.11.8
launch-screen@1.0.11
livedata@1.0.18
logging@1.0.12
meteor@1.1.14
meteor-base@1.0.4
minifier-css@1.1.11
minifier-js@1.1.11
minimongo@1.0.16
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.6.1
modules-runtime@0.6.3
mongo@1.1.7
mongo-id@1.0.4
npm-mongo@1.4.43
observe-sequence@1.0.11
ordered-dict@1.0.7
package-version-parser@3.0.8
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_2
practicalmeteor:mocha-core@0.1.4
practicalmeteor:sinon@1.14.1_2
promise@0.6.7
random@1.0.9
reactive-var@1.0.9
reload@1.1.8
retry@1.0.7
routepolicy@1.0.10
sanjo:meteor-files-helpers@1.2.0_1
sanjo:meteor-version@1.0.0
spacebars@1.0.11
spacebars-compiler@1.0.11
standard-minifier-css@1.0.6
standard-minifier-js@1.0.6
templating@1.1.9
templating-tools@1.0.4
tmeasday:check-npm-versions@0.3.1
tmeasday:test-reporter-helpers@0.2.1
tracker@1.0.13
ui@1.0.11
underscore@1.0.8
url@1.0.9
webapp@1.2.8
webapp-hashing@1.0.9
```

###.babel.rc

```js
{
  "presets": [
    "meteor",
    "es2015",
    "stage-1"
  ],

  "plugins": [
    "transform-decorators-legacy"
  ]
}

```

### package.json

```js
{
  "name": "oppinut-neo",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "angular": "^1.5.5",
    "angular-animate": "^1.5.5",
    "angular-meteor": "^1.3.10",
    "angular-touch": "^1.5.5",
    "angular2-now": "^1.1.6",
    "bootstrap-sass": "^3.3.6",
    "meteor-node-stubs": "~0.2.0",
    "underscore": "^1.8.3",
    "underscore.string": "^3.3.4"
  },
  "devDependencies": {
    "babel-eslint": "^6.0.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-meteor": "^6.8.1",
    "babel-preset-stage-1": "^6.5.0",
    "babel-runtime": "^6.9.0",
    "eslint": "^2.9.0",
    "eslint-config-airbnb-base": "^2.0.0",
    "eslint-import-resolver-meteor": "^0.1.3",
    "eslint-plugin-import": "^1.6.1",
    "eslint-plugin-react": "^5.0.1"
  }
}
```

**Comment by gadicc** [comment]
Thanks for the detailed report!  Damn, I specifically tested test-mode before publishing the latest updates, but I guess I missed some edge cases.  However, with Meteor 1.3.3 beta.0 just out with official `.babelrc` support, I'm dropping support for this in our project.  You should switch to that and meteor-hmr support (in case you're using that too) will be soon to follow.

**Comment by myknbani** [comment]
Thanks!  I also encountered issues with 1.3.3-beta.0, but I guess I'll have to be patient.
